site_name: COMP423 Course Notes
theme:
  name: material
  palette: 
  # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

  # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
  #Create clipboards
  features:
    - content.code.copy
    - content.code.annotate
    - content.code.select

markdown_extensions:
#enables syntax highlighting on code blocks and inline code blocks
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.betterem
  - admonition
  - attr_list
  - md_in_html
